#!/bin/sh
intltool-extract --type=gettext/glade usr/share/linuxmint/mintLocale/mintLocale.ui
intltool-extract --type=gettext/glade usr/share/linuxmint/mintLocale/install_remove.ui 
intltool-extract --type=gettext/glade usr/share/linuxmint/mintLocale/add.ui
xgettext --language=Python --keyword=_ --keyword=N_ --output=mintlocale.pot usr/share/linuxmint/mintLocale/*.py usr/share/linuxmint/mintLocale/*.ui.h generate_desktop_files
rm -f usr/share/linuxmint/mintLocale/*.ui.h
